### ISSUE TITLE
Could you add EIM to melpa please?

### ISSUE THREAD

**Issue by sunlin7** [wenbinye/emacs-eim#3]
Hi Wenbin:

Eim is the fast and the best Chinese input method I have been used. 
Thank you for your work, it's really very great.

And could you add EIM to melpa and the user can install and upgrade with package manager?
                           ("melpa" . "http://melpa.milkbox.net/packages/")
Best Regards
Sunline

**Comment by cmrshieh** [comment]
+1

**Comment by sunlin7** [comment]
Close this issue for there is fork at https://github.com/zilongshanren/chinese-wbim.
